Add repository to helm (#15)
* Add repository to helm

* Fix helm value for repository

* Fix helm value for repository

* Fix latest tag replacment

* Fix latest tag replacment

* Add mandatory field

* Fix postgresql composition

* Fix repository xrd

---------

Co-authored-by: Märt Erlenheim <mart.erlenheim@entigo.com>
Co-authored-by: Märt Erlenheim <71629159+entigo-mart-erlenheim@users.noreply.github.com>

diff --git a/.github/workflows/helm.yml b/.github/workflows/helm.yml
--- a/.github/workflows/helm.yml
+++ b/.github/workflows/helm.yml
@@ -65,6 +65,16 @@ jobs:
             | jq -r '[.[] | select(.metadata.container.tags[] | startswith("v"))] | sort_by(.created_at) | .[-1].metadata.container.tags[] | select(startswith("v"))' \
             | head -n 1)
 
+          REPOSITORY_TAG=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/orgs/entigolabs/packages/container/platform-apis-repository/versions" \
+            | jq -r '[.[] | select(.metadata.container.tags[] | startswith("v"))] | sort_by(.created_at) | .[-1].metadata.container.tags[] | select(startswith("v"))' \
+            | head -n 1)
+
+          REPOSITORY_FN_TAG=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/orgs/entigolabs/packages/container/platform-apis-repository-fn/versions" \
+            | jq -r '[.[] | select(.metadata.container.tags[] | startswith("v"))] | sort_by(.created_at) | .[-1].metadata.container.tags[] | select(startswith("v"))' \
+            | head -n 1)
+
           ZONE_TAG=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/orgs/entigolabs/packages/container/platform-apis-zone/versions" \
             | jq -r '[.[] | select(.metadata.container.tags[] | startswith("v"))] | sort_by(.created_at) | .[-1].metadata.container.tags[] | select(startswith("v"))' \
@@ -94,6 +104,16 @@ jobs:
             echo "Failed to fetch postgresql-fn tag"
             exit 1
           fi
+
+          if [ -z "$REPOSITORY_TAG" ] || [ "$REPOSITORY_TAG" = "null" ]; then
+            echo "Failed to fetch repository tag"
+            exit 1
+          fi
+          if [ -z "$REPOSITORY_FN_TAG" ] || [ "$REPOSITORY_FN_TAG" = "null" ]; then
+            echo "Failed to fetch repository-fn tag"
+            exit 1
+          fi
+
           if [ -z "$ZONE_TAG" ] || [ "$ZONE_TAG" = "null" ]; then
             echo "Failed to fetch zone tag"
             exit 1
@@ -114,23 +134,15 @@ jobs:
             exit 1
           fi
 
-          echo "POSTGRESQL_TAG=$POSTGRESQL_TAG" >> $GITHUB_ENV
-          echo "POSTGRESQL_FN_TAG=$POSTGRESQL_FN_TAG" >> $GITHUB_ENV
-          echo "ZONE_TAG=$ZONE_TAG" >> $GITHUB_ENV
-          echo "WEBAPP_TAG=$WEBAPP_TAG" >> $GITHUB_ENV
-          echo "WEBACCESS_TAG=$WEBACCESS_TAG" >> $GITHUB_ENV
-          echo "CRONJOB_TAG=$CRONJOB_TAG" >> $GITHUB_ENV
-
-          echo "Latest tags: postgresql=$POSTGRESQL_TAG, postgresql-fn=$POSTGRESQL_FN_TAG, zone=$ZONE_TAG"
-      - name: Update Values with Latest Tags
-        run: |
           echo "Updating tags..."
-          yq -i '.postgresql.package.tag = "${{ env.POSTGRESQL_TAG }}"' ${{ env.CHART_PATH }}/values.yaml
-          yq -i '.postgresql.function.tag = "${{ env.POSTGRESQL_FN_TAG }}"' ${{ env.CHART_PATH }}/values.yaml
-          yq -i '.zone.package.tag = "${{ env.ZONE_TAG }}"' ${{ env.CHART_PATH }}/values.yaml
-          yq -i '.webapp.package.tag = "${{ env.WEBAPP_TAG }}"' ${{ env.CHART_PATH }}/values.yaml
-          yq -i '.webaccess.package.tag = "${{ env.WEBACCESS_TAG }}"' ${{ env.CHART_PATH }}/values.yaml
-          yq -i '.cronjob.package.tag = "${{ env.CRONJOB_TAG }}"' ${{ env.CHART_PATH }}/values.yaml
+          yq -i ".postgresql.package.tag = \"$POSTGRESQL_TAG\"" ${{ env.CHART_PATH }}/values.yaml
+          yq -i ".postgresql.function.tag = \"$POSTGRESQL_FN_TAG\"" ${{ env.CHART_PATH }}/values.yaml
+          yq -i ".repository.package.tag = \"$REPOSITORY_TAG\"" ${{ env.CHART_PATH }}/values.yaml
+          yq -i ".repository.function.tag = \"$REPOSITORY_FN_TAG\"" ${{ env.CHART_PATH }}/values.yaml
+          yq -i ".zone.package.tag = \"$ZONE_TAG\"" ${{ env.CHART_PATH }}/values.yaml
+          yq -i ".webapp.package.tag = \"$WEBAPP_TAG\"" ${{ env.CHART_PATH }}/values.yaml
+          yq -i ".webaccess.package.tag = \"$WEBACCESS_TAG\"" ${{ env.CHART_PATH }}/values.yaml
+          yq -i ".cronjob.package.tag = \"$CRONJOB_TAG\"" ${{ env.CHART_PATH }}/values.yaml
           echo "After update:"
           cat ${{ env.CHART_PATH }}/values.yaml
 
@@ -144,8 +156,11 @@ jobs:
           echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
           echo "Updated version to $NEW_VERSION"
       - name: Login to GHCR
-        run: |
-          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} --username ${{ github.actor }} --password-stdin
+        uses: docker/login-action@v3
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
       - name: Package Helm Chart
         run: helm package ${{ env.CHART_PATH }}
       - name: Push Helm Chart to GHCR
